### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by Francois284Modz** [Riziebtw/RzyFixer#1]
hey bro nice work but i cant compile it can you compile it and realse the compiled version

**Comment by WolfDust** [comment]
yeahh me too i cant compile

**Comment by ardasenkall** [comment]
me too

**Comment by Riziebtw** [comment]
Hello, thanks for creating an issue.
I'm gonna push a .exe release in few mins.

**Comment by Riziebtw** [comment]
Just added debug.rar file.
